import {
  BufferAttribute,
  BufferGeometry,
  Color,
  DynamicDrawUsage,
  Group,
  InstancedMesh,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  Object3D,
  Quaternion,
  Vector3,
  type WebGLProgramParametersWithUniforms,
} from 'three'
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js'
import type { FireSimulation } from './FireSimulation'

export interface FynbosVariant {
  /** Name of the live plant Empty in the GLB. */
  live: string
  /** Name of the burnt remnant Empty in the GLB. */
  burnt: string
  /** Relative frequency. */
  weight: number
  /** Uniform scale range. Plants are scaled up so they read from the demo camera distance. */
  scale: [number, number]
}

export interface FynbosOptions {
  /** Total plants across all variants. */
  count?: number
  variants?: FynbosVariant[]
  seed?: number
}

export const defaultVariants: FynbosVariant[] = [
  { live: 'protea', burnt: 'protea_burnt', weight: 0.28, scale: [3.0, 4.6] },
  { live: 'restio', burnt: 'restio_burnt', weight: 0.42, scale: [2.8, 4.2] },
  { live: 'erica', burnt: 'erica_burnt', weight: 0.3, scale: [3.2, 4.8] },
]

/**
 * Instanced fynbos scattered over the fire's fuel cells. Every plant reads the fire's state
 * texture in its vertex shader: as the cell chars the live plant shrinks away and its burnt
 * remnant grows in its place, and both glow with embers while the cell is alight.
 *
 * Assets come from `public/models/fynbos.glb`, generated by `tools/blender/fynbos.py`.
 *
 *   const fynbos = new Fynbos(sim, gltf.scene, { count: 16000 })   // after sim.sampleTerrain()
 *   fynbos.update()                                                 // every frame
 */
export class Fynbos {
  readonly group = new Group()
  readonly meshes: InstancedMesh[] = []
  private uniforms = {
    uState: { value: null as unknown },
    uSize: { value: 0 },
    uTime: { value: 0 },
  }
  private sim: FireSimulation

  constructor(sim: FireSimulation, assets: Object3D, options: FynbosOptions = {}) {
    this.sim = sim
    const { count = 16000, variants = defaultVariants, seed = 5 } = options
    this.uniforms.uState.value = sim.stateTexture
    this.uniforms.uSize.value = sim.options.size
    this.group.name = 'fynbos'

    const rnd = seeded(seed)
    const points = sim.scatter(count, seed)
    const total = variants.reduce((s, v) => s + v.weight, 0)

    // bucket placements per variant
    const buckets = variants.map(() => [] as number[])
    for (let p = 0; p < points.length / 4; p++) {
      let r = rnd() * total
      let k = 0
      while (k < variants.length - 1 && r >= variants[k].weight) r -= variants[k++].weight
      buckets[k].push(p)
    }

    const m = new Matrix4()
    const q = new Quaternion()
    const pos = new Vector3()
    const scl = new Vector3()
    const up = new Vector3(0, 1, 0)
    variants.forEach((variant, k) => {
      const ids = buckets[k]
      if (ids.length === 0) return
      const live = mergeWithVertexColours(assets, variant.live)
      const burnt = mergeWithVertexColours(assets, variant.burnt)
      const liveMesh = new InstancedMesh(live, this.material(0), ids.length)
      const burntMesh = new InstancedMesh(burnt, this.material(1), ids.length)
      ids.forEach((p, i) => {
        const fuel = points[p * 4 + 3]
        const s = (variant.scale[0] + rnd() * (variant.scale[1] - variant.scale[0])) * (0.75 + 0.5 * fuel)
        pos.set(points[p * 4], points[p * 4 + 1] - 0.15, points[p * 4 + 2])
        q.setFromAxisAngle(up, rnd() * Math.PI * 2)
        scl.set(s, s, s)
        m.compose(pos, q, scl)
        liveMesh.setMatrixAt(i, m)
        burntMesh.setMatrixAt(i, m)
      })
      for (const mesh of [liveMesh, burntMesh]) {
        mesh.instanceMatrix.setUsage(DynamicDrawUsage)
        mesh.instanceMatrix.needsUpdate = true
        mesh.frustumCulled = false
        mesh.name = `${variant.live}-${mesh === liveMesh ? 'live' : 'burnt'}`
        this.meshes.push(mesh)
        this.group.add(mesh)
      }
    })

    sim.group.add(this.group)
  }

  /** Call every frame so embers flicker. */
  update() {
    this.uniforms.uTime.value = this.sim.elapsed
  }

  dispose() {
    this.sim.group.remove(this.group)
    for (const mesh of this.meshes) {
      mesh.geometry.dispose()
      ;(mesh.material as MeshStandardMaterial).dispose()
      mesh.dispose()
    }
  }

  /** Standard material patched to read the fire state per instance. mode 0 = live, 1 = remnant. */
  private material(mode: 0 | 1) {
    const mat = new MeshStandardMaterial({ vertexColors: true, roughness: 0.9, metalness: 0 })
    const uniforms = this.uniforms
    mat.customProgramCacheKey = () => `fynbos-${mode}`
    mat.onBeforeCompile = (shader: WebGLProgramParametersWithUniforms) => {
      Object.assign(shader.uniforms, uniforms, { uMode: { value: mode } })
      shader.vertexShader = shader.vertexShader
        .replace(
          '#include <common>',
          `#include <common>
          uniform sampler2D uState;
          uniform float uSize;
          uniform float uMode;
          varying float vBurn;
          varying float vHeat;`,
        )
        .replace(
          '#include <begin_vertex>',
          `vec3 ip = instanceMatrix[3].xyz;
          vec4 st = texture2D(uState, vec2(ip.x / uSize + 0.5, 0.5 - ip.z / uSize));
          vBurn = st.g;
          vHeat = st.r;
          float gone = smoothstep(0.2, 0.65, st.g);
          // live plants wilt slightly as they heat, then collapse; remnants rise in their place
          float s = uMode < 0.5 ? (1.0 - gone) * (1.0 - 0.15 * st.r) : gone;
          vec3 transformed = vec3(position) * s;`,
        )
      shader.fragmentShader = shader.fragmentShader
        .replace(
          '#include <common>',
          `#include <common>
          uniform float uTime;
          uniform float uMode;
          varying float vBurn;
          varying float vHeat;`,
        )
        .replace(
          '#include <color_fragment>',
          `#include <color_fragment>
          if (uMode < 0.5) diffuseColor.rgb = mix(diffuseColor.rgb, vec3(0.05, 0.04, 0.035), smoothstep(0.0, 0.45, vBurn) * 0.9);`,
        )
        .replace(
          '#include <emissivemap_fragment>',
          `#include <emissivemap_fragment>
          float flick = 0.7 + 0.3 * sin(uTime * 11.0 + gl_FragCoord.x * 0.05 + gl_FragCoord.y * 0.03);
          totalEmissiveRadiance += vec3(1.0, 0.36, 0.05) * vHeat * flick * (uMode < 0.5 ? 1.4 : 0.6);`,
        )
    }
    return mat
  }
}

/**
 * Merge every mesh under the named Empty into one geometry with a vertex colour attribute
 * baked from each part's material colour, so a whole plant is one instanced draw call.
 */
function mergeWithVertexColours(assets: Object3D, name: string) {
  const root = assets.getObjectByName(name)
  if (!root) throw new Error(`Fynbos asset "${name}" not found in the GLB`)
  root.updateMatrixWorld(true)
  const inverseRoot = new Matrix4().copy(root.matrixWorld).invert()
  const parts: BufferGeometry[] = []
  const colour = new Color()
  root.traverse((o) => {
    const mesh = o as Mesh
    if (!mesh.isMesh) return
    const g = mesh.geometry.clone()
    // strip everything but position and normal so parts merge cleanly
    for (const key of Object.keys(g.attributes)) if (key !== 'position' && key !== 'normal') g.deleteAttribute(key)
    g.applyMatrix4(new Matrix4().multiplyMatrices(inverseRoot, mesh.matrixWorld))
    const material = (Array.isArray(mesh.material) ? mesh.material[0] : mesh.material) as MeshStandardMaterial
    colour.copy(material.color ?? new Color('#6f7f55'))
    const n = g.attributes.position.count
    const colours = new Float32Array(n * 3)
    for (let i = 0; i < n; i++) {
      colours[i * 3] = colour.r
      colours[i * 3 + 1] = colour.g
      colours[i * 3 + 2] = colour.b
    }
    g.setAttribute('color', new BufferAttribute(colours, 3))
    parts.push(g)
  })
  if (parts.length === 0) throw new Error(`Fynbos asset "${name}" has no meshes`)
  const merged = mergeGeometries(parts, false)
  if (!merged) throw new Error(`Could not merge parts of "${name}"`)
  parts.forEach((g) => g.dispose())
  return merged
}

function seeded(seed: number) {
  let s = seed >>> 0
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0
    return s / 0xffffffff
  }
}
